version: '3.8'

services:
  ws-info-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${FASTAPI_PORT}:80"
    depends_on:
      - mongo-info-ws
    networks:     
      - ws_app_network

  mongo-info-ws:
    container_name: mongo-info-ws
    image: "mongo"
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
        MONGO_INITDB_DATABASE: weather
    volumes:
      - ws-info-data:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:    
      - ws_app_network

volumes:
  ws-info-data:

networks:
  ws_app_network:
    driver: bridge