# docker/docker-compose.yml

version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${FASTAPI_PORT}:80"
    depends_on:
      - mongo-info
    networks:     
      - ws_app_network

  mongo-info:
    image: "mongo"
    ports:
      - "${MONGODB_PORT}:27017"
    networks:    
      - ws_app_network

networks:
  ws_app_network:
    driver: bridge