version: '3.8'

services:
  ws-info-service:
    build:
      context: ..
      dockerfile: docker_ws/Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port ${UVICORN_PORT}
    hostname: ws-info-service
    container_name: ws-info-service
    volumes:
      - ../app/:/app/
    ports:
      - "${WS_INFO_SERVICE_PORT}:${UVICORN_PORT}"
    environment:
        MONGO_URL: "${WS_INFO_SERVICE_MONGO_URL}"
        WS_INFO_SERVICE_HOST_URL: "${WS_INFO_SERVICE_HOST_URL}"
    depends_on:
      - mongo-info-ws
    networks:     
      - ${NETWORK_NAME}

  mongo-info-ws:
    container_name: mongo-info-ws
    image: "mongo"
    ports:
      - "${MONGO_DB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-info-data:/data/db
      - ./mangodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:    
      - ${NETWORK_NAME}

volumes:
  mongo-info-data:

networks:
  ws_app_network:
    external: true